### ISSUE TITLE
你好，请问这套代码需要和apache，mysql配合吗？

### ISSUE THREAD

**Issue by AloneFrog** [laobubu/ssland#3]

**Comment by laobubu** [comment]
不需要

2016年8月30日 下午2:03，"AloneFrog" notifications@github.com写道：

**Comment by laobubu** [comment]
但是还是建议加上一层反向代理，因为 Python 的 HTTP Server 不是很靠谱，容易被非法请求搞瘫痪…

2016年8月30日 下午2:04，"laobubu" laobubu@gmail.com写道：

**Comment by AloneFrog** [comment]
感谢，这么快回复，请问可以加个QQ交流吗？

**Comment by AloneFrog** [comment]
你好，我已经配置完成了，请问是用浏览器直接访问我的IP地址吗？

**Comment by laobubu** [comment]
see #4
