### ISSUE TITLE
views_generic.py死循环导致cpu撑到100%

### ISSUE THREAD

**Issue by shougaoshougao** [laobubu/ssland#9]
我打开debug，加了点日志，定位到views_generic.py这段循环跳不出来了，求修复
 while True:
        _percent = get_percent(_gtime)
        if _percent > 100: break
        if _percent > 0:
            grids.append({
                'x_percent': _percent,
                'time': _gtime
            })

**Comment by shougaoshougao** [comment]
#10

**Comment by laobubu** [comment]
Thanks for your contribution!
